export const BASE_URL = 'BASE_URL';
export const JWT_SECRET = 'JWT_SECRET';
export const SENDGRID_API_KEY = 'SENDGRID_API_KEY';
export const SENDGRID_SENDER = 'SENDGRID_SENDER';
export const SENDGRID_AUTH_TEMPLATE = 'SENDGRID_AUTH_TEMPLATE';
export const SENDGRID_VERIFICATION_TEMPLATE_ID =
  'SENDGRID_VERIFICATION_TEMPLATE_ID';
export const BASE_URL = 'BASE_URL';
